#############################
#
# Training for freq sr model
#
#############################

Executable   = train.sh
Log          = train.log
Output       = train.stdout
Error        = train.stderr
# Use this to make sure 1 gpu is available. The key words are case insensitive.
Request_gpus = 1
# Note: to use multiple CPUs instead of the default (one CPU), use request_cpus as well
Request_cpus = 3
# "Queue" means add the setup until this line to the queue.
Queue
